### ISSUE TITLE
sync loading warning message

### ISSUE THREAD

**Issue by leonardomontes** [recurly/pay-with-amazon#16]
Started getting this warning in Google Chrome. The script needs to be changed to async loading.

`A parser-blocking, cross site (i.e. different eTLD+1) script, https://static-na.payments-amazon.com/OffAmazonPayments/us/js/Widgets.js?sellerId=A3HQTVNFC7QR7Y, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.`

**Comment by chrissrogers** [comment]
@leonardomontes thanks very much for the heads-up. I've logged this and will update here as we progress on the change. Cheers!

**Comment by max8hine** [comment]
The `document.write` issue is broken on me in Chrome Version 80.0.3987.122 (Official Build) (64-bit)

I've had an issue `Uncaught TypeError: Cannot read property 'getElementsByTagName' of null`.


Which I believe I need initial **PayWithAmazon** after Document loaded, so I did this:

```javascript
document.addEventListener("DOMContentLoaded", function(event) {
  var payWithAmazon = new PayWithAmazon(config);
});
```

Then, the above error occurs and the page stop rendering, and point out at 
https://github.com/recurly/pay-with-amazon/blob/6cc6aae41c22c3cd6f90a5003ee6d8c65fbf1b64/index.js#L78-L80

I've fixed by below code:

```javascript
var script = document.createElement('script');  
script.src = 'https://static-na.payments-amazon.com/OffAmazonPayments/us'
  + (this.config.production ? '' : '/sandbox')
  + '/js/Widgets.js?sellerId='
  + this.config.sellerId;  
document.head.appendChild(script);
```

**Comment by chrissrogers** [comment]
@max8hine thank you for the detailed run-through, and apologies for the delay in response. I'll test your change proposal and we'll get to updating this library to remove `document.write`. Initially, this was a requirement for OffAmazonPayments, but I suspect this restriction will have been lifted by now.
